test 17

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -1,25 +1,25 @@
 # This workflow will build a golang project
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
 
-name: Go
+name: Go Build and Release
 
 on:
-  # push:
-  #   tags:
-  #     - v*
-  workflow_dispatch:
-    inputs:
-      tag:
-        description: "The tag version you want to build"
-        required: true
-        type: string
-        default: "v0.1"
+  push:
+    tags:
+      - v*
+  # workflow_dispatch:
+  #   inputs:
+  #     tag:
+  #       description: "The tag version you want to build"
+  #       required: true
+  #       type: string
+  #       default: "v0.1"
 
 env:
-  APP_NAME: rrmcd
+  APP_NAME: rrcmd
   BUILD_DIR: build
-  # BUILD_TAG: ${{ github.ref_name }}
-  BUILD_TAG: ${{ github.event.inputs.tag }}
+  BUILD_TAG: ${{ github.ref_name }}
+  # BUILD_TAG: ${{ github.event.inputs.tag }}
 
 jobs:
 
@@ -33,19 +33,28 @@ jobs:
         arch: [amd64, arm64]
 
     steps:
-    - uses: actions/checkout@v4
+    - name: Checkout
+      uses: actions/checkout@v4
 
-    - name: Set up Go
+    - name: Golang
       uses: actions/setup-go@v5
       with:
         go-version: ${{ matrix.go-version }}
 
     - name: Build
       run: |
+        exit 1
         mkdir -p ${{ env.BUILD_DIR }}
         GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ${{ env.BUILD_DIR }}/${{ env.APP_NAME }}_${{ matrix.os }}_${{ matrix.arch }} -v ./...
-  
-    - name: Release
+
+    - name: Check
+      run: |
+        if [ ! -f ${{ env.BUILD_DIR }}/${{ env.APP_NAME }}_${{ matrix.os }}_${{ matrix.arch }} ]; then
+          echo "Build failed or output file not found!"
+          exit 1
+        fi
+
+    - name: Create Release
       uses: softprops/action-gh-release@v2
       env:
         GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
@@ -55,7 +64,12 @@ jobs:
         body: "远程执行命令, 多主机并发"
         files: ${{ env.BUILD_DIR }}/${{ env.APP_NAME }}_${{ matrix.os }}_${{ matrix.arch }}
 
-    - name: Delete workflow runs
+  clean:
+    runs-on: ubuntu-latest
+    needs: build
+
+    steps:
+    - name: Delete workflow
       uses: Mattraks/delete-workflow-runs@v2
       if: always()
       with:
@@ -63,7 +77,7 @@ jobs:
         retain_days: 1
         keep_minimum_runs: 3
 
-    - name: Delete older Releases
+    - name: Delete Release
       uses: dev-drprasad/delete-older-releases@v0.3.4
       env:
         GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
